-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Company"
(
    "CompanyId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "Company_pkey" PRIMARY KEY ("CompanyId")
);

CREATE TABLE IF NOT EXISTS public."Contract"
(
    "ContractID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DateOfContract" date,
    "DateOfPayment" date,
    "CostOfObject" integer,
    "EmployeeID" integer NOT NULL,
    "ContractType" character varying(20) COLLATE pg_catalog."default",
    "OwnerPassportNumber" integer NOT NULL,
    "ClientPassportNumber" integer NOT NULL,
    CONSTRAINT "Contract_pkey" PRIMARY KEY ("ContractID")
);

CREATE TABLE IF NOT EXISTS public."District"
(
    "DistrictId" character(18) COLLATE pg_catalog."default" NOT NULL,
    "City" text COLLATE pg_catalog."default",
    "Name" text COLLATE pg_catalog."default",
    CONSTRAINT "District_pkey" PRIMARY KEY ("DistrictId")
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "EmployeeID" integer NOT NULL,
    "Surname" character varying(20) COLLATE pg_catalog."default",
    "Name" character varying(20) COLLATE pg_catalog."default",
    "CompanyId" integer NOT NULL,
    CONSTRAINT "Employee_pkey" PRIMARY KEY ("EmployeeID")
);

CREATE TABLE IF NOT EXISTS public."PassportClient"
(
    "PassportNumber" integer NOT NULL,
    "Date" date,
    "CodeOffice" integer,
    "Family" character varying(18) COLLATE pg_catalog."default",
    "Name" character varying(20) COLLATE pg_catalog."default",
    "Surname" character varying(20) COLLATE pg_catalog."default",
    "City" text COLLATE pg_catalog."default",
    "Age" integer,
    CONSTRAINT "PassportClient_pkey" PRIMARY KEY ("PassportNumber")
);

CREATE TABLE IF NOT EXISTS public."RealEastateObject"
(
    "ObjectId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Address" text COLLATE pg_catalog."default",
    "Square" integer,
    "ObjectType" text COLLATE pg_catalog."default",
    "DistrictId" character(18) COLLATE pg_catalog."default" NOT NULL,
    "OwnerPassportNumber" integer NOT NULL,
    CONSTRAINT "RealEstateObject_pkey" PRIMARY KEY ("ObjectId")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Users_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id integer NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
    username character varying(50) COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default",
    event_timestamp timestamp without time zone DEFAULT now(),
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Contract"
    ADD CONSTRAINT "Contract_ClientPassportNumber_fkey" FOREIGN KEY ("ClientPassportNumber")
    REFERENCES public."PassportClient" ("PassportNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Contract_ClientPassportNumber_fkey"
    ON public."Contract"("ClientPassportNumber");


ALTER TABLE IF EXISTS public."Contract"
    ADD CONSTRAINT "Contract_EmployeeID_fkey" FOREIGN KEY ("EmployeeID")
    REFERENCES public."Employee" ("EmployeeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Contract"
    ADD CONSTRAINT "Contract_OwnerPassportNumber_fkey" FOREIGN KEY ("OwnerPassportNumber")
    REFERENCES public."PassportClient" ("PassportNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT "Employee_CompanyId_fkey" FOREIGN KEY ("CompanyId")
    REFERENCES public."Company" ("CompanyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."RealEastateObject"
    ADD CONSTRAINT "RealEstateObject_DistrictId_fkey" FOREIGN KEY ("DistrictId")
    REFERENCES public."District" ("DistrictId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."RealEastateObject"
    ADD CONSTRAINT "RealEstateObject_OwnerPassportNumber_fkey" FOREIGN KEY ("OwnerPassportNumber")
    REFERENCES public."PassportClient" ("PassportNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;